baseURL = 'https://coldbrewlabs.ca/'
languageCode = 'en-us'
title = 'Jacob Mammoliti'
theme = 'techblog'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = false
    noClasses = false
    tabWidth = 4

[params]
  description = 'Technologist based in Toronto, Canada focused on Cloud and Container Security.'
  showAbout = false
  footerText = ''
  googleAnalytics = 'G-77N7X1MF11' # Set your GA4 Measurement ID here, e.g., G-XXXXXXXXXX
  
  # Social media links
  [params.social]
    github = 'https://github.com/jacobmammoliti'
    linkedin = 'https://linkedin.com/in/jacobmammoliti'
  
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    name = 'Posts'
    url = '/posts/'
    weight = 20
